[package]
name = "parent"
version = "0.1.0"

[[bin]]
name = "parent"
path = "src/main.rs"

[lib]
name = "parent"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
libloading = "0.5.0"
migrant_lib = "0.23.0"
